"""empty message

Revision ID: 6f553974726a
Revises: 45041c712dc4
Create Date: 2022-05-16 07:10:34.849218

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6f553974726a'
down_revision = '45041c712dc4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('blog', sa.Column('title', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('blog', 'title')
    # ### end Alembic commands ###
